app/blueprints/blood.py
from flask import Blueprint, render_template
from app.models.tables import BloodType
from app.models.forms import BloodTypeForm

blood_blueprint = Blueprint('blood', __name__)

@blood_blueprint.route('/blood', methods=['GET'])
def blood():
    bloodType = BloodTypeForm()
    blood_Type = BloodType.query.filter_by().all()
    
    return render_template('test.html',bloodType=bloodType)

app/blueprints/person.py
from flask import Blueprint, render_template, request, redirect
from app import db
from app.person.models import Person
from app.person.forms import PersonRegistrationForm

from datetime import datetime, date

person_blueprint = Blueprint('person', __name__)

@person_blueprint.route('/person', methods=['POST', 'GET'])
def person():
    personRegistration = PersonRegistrationForm()

    if request.method == 'POST':
        print('POST')
    else:
        print('Não POST')
    number = personRegistration.number.data  #Number
    print(type(number))
    if number == '' or number == 'sn':
        number = 0
    print("BD -> {}" .format(number))
    if personRegistration.validate_on_submit():
        #Person Identification
        document_type = personRegistration.document_type.data  #0 - PF || 1 - PJ
        registration_card = personRegistration.registration_card.data  #CPF/CNPJ
        identification =  str.upper(personRegistration.identification.data)  #Identification
        if identification == '':
            identification = None
        first_name = str.upper(personRegistration.first_name.data)  #Name
        second_name = str.upper(personRegistration.second_name.data)  #Second name
        birth_day = personRegistration.birth_day.data  #Birth day
        if birth_day == '':
            birth_day = datetime(1900, 1, 1).date()
        nick_name = str.upper(personRegistration.nick_name.data)  #Nickname
        if nick_name == '':
            nick_name = None
        father_name = str.upper(personRegistration.father_name.data)  #Father name
        if father_name == '':
            father_name = None
        mother_name = str.upper(personRegistration.mother_name.data)  #Mother name
        if mother_name == '':
            mother_name = None
        #Contact
        email = str.lower(personRegistration.email.data)  #E-mail
        phone_number = personRegistration.phone_number.data  #Phone
        if phone_number == '':
            phone_number = None
        cellphone_number = personRegistration.cellphone_number.data  #Cell phone

        #Address
        postal_code = personRegistration.postal_code.data  #Postal code
        if postal_code == '':
            postal_code = None
        street = str.upper(personRegistration.street.data)  #Street
        if street == '':
            street = None
        number = str.upper(personRegistration.number.data)  #Number
        if number == 'SN' or number == '':
            number = 0
        complement = str.upper(personRegistration.complement.data)  #Complement
        if complement == '':
            complement = None
        neighborhood = str.upper(personRegistration.neighborhood.data)  #Neighborhood
        if neighborhood == '':
            neighborhood = None
        city = str.upper(personRegistration.city.data)  #City
        if city == '':
            city = None
        state = str.upper(personRegistration.state.data)  #State
        if state == '':
            state = None
        country = str.upper(personRegistration.country.data)  #Country
        if country == '':
            country = None

        #Observations
        observations = personRegistration.observations.data
        if observations == '':
            observations = None

        #Action DateTime
        created_at = datetime.now()  #Created at
        updated_at = None  #Updated at  #Deleted(soft delete)
        deleted = 0  #Deleted(soft delete)
        deleted_at = None  #Deleted at(soft delete)

        print('BD: {} -> NN: {}'.format(birth_day, nick_name))
        new_person = Person(document_type=document_type, registration_card=registration_card, first_name=first_name, second_name=second_name, birth_day=birth_day, nick_name=nick_name, identification=identification, father_name=father_name, mother_name=mother_name, email=email, phone_number=phone_number, cellphone_number=cellphone_number, postal_code=postal_code, street=street, number=number, complement=complement, neighborhood=neighborhood, city=city, state=state, country=country, observations=observations, created_at=created_at, updated_at=updated_at, deleted=deleted, deleted_at=deleted_at)

        db.session.add(new_person)
        db.session.commit()
        # Criar listagem e fazer redirecionamento para ela.
        return redirect('../')
    else:
        #return personRegistration.errors
        print(personRegistration.errors)
    
    return render_template('person/form/personRegister.html', personRegistration = personRegistration)

app/blueprints/religion.py
from flask import Blueprint, render_template, url_for, request, redirect
from app import db
from app.religion.models import Religion
from app.religion.forms import ReligionForm

from datetime import datetime, date

religion_blueprint = Blueprint('religion', __name__)

@religion_blueprint.route('/religion', methods=['GET', 'POST'])
def religionList():
    #religionList = ReligionList()

    religion_list = Religion.query.filter_by().all()
    return render_template('religion/table/religions.html', religion_list = religion_list)#,religionList=religionList)

@religion_blueprint.route('/religionRegister', methods=['GET', 'POST'])
def religion():
    religionForm = ReligionForm()

    if religionForm.validate_on_submit():
        #Religion
        religion = religionForm.religion.data

        #Denomination
        denomination = religionForm.denomination.data
        if denomination == '':
            denomination = None

        #Observations
        observations = religionForm.observations.data
        if observations == '':
            observations = None

        #Action DateTime
        created_at = datetime.now()  #Created at
        updated_at = None  #Updated at  #Deleted(soft delete)
        deleted = 0  #Deleted(soft delete)
        deleted_at = None  #Deleted at(soft delete)

        new_religion = Religion(religion=religion, denomination=denomination, observations=observations, created_at=created_at, updated_at=updated_at, deleted=deleted, deleted_at=deleted_at)

        db.session.add(new_religion)
        db.session.commit()
        # Criar listagem e fazer redirecionamento para ela.
        return redirect(url_for('religion.religionList'))

    else:
        #return personRegistration.errors
        print(religionForm.errors)

    return render_template('religion/form/religionRegister.html', religionForm=religionForm)

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>{% block title %}Flask{% endblock %} </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('index')}}">Project Flask</a>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('blood.blood')}}">Sangue</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('person.person')}}">Pessoa</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('religion.religion')}}">Religiões</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %} {% endblock %}
    <hr>
    <footer class="container">
        <p>Eric Marques&copy; 2020</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

    <script src="{{ url_for('static', filename='/js/bootstrap.bundle.min.js') }}" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='/js/bootstrap.min.js') }}" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %} {% block title %}{{ super() }} - Index{% endblock %} {% block content %}
<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet
                    risus.
                </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>
    </div>
    <!-- /container -->

</main>
{% endblock %}

app/templates/test.html
{%extends 'base.html'%}{%block title%}{{super()}} - Testes {%endblock%}{%block content%} {{bloodType.csrf_token}}{{bloodType.hidden_tag()}}
<h1>Blood Type</h1> {%for bloodType in bloodType%} {{bloodType}} {%endfor%} {%endblock%}